---
# tasks file for epel

- name: install epel
  block:
    - name: install epel gpg key
      rpm_key:
        key: "{{ epel_gpg_key }}"
        state: present

    - name: install epel-release
      package:
        name: "{{ epel_url }}"
        state: present
      notify:
        - yum update cache
  when:
    - ansible_distribution in [ "Amazon", "CentOS", "RedHat" ]
    - ansible_distribution_major_version in [ "7", "8", "2018" ]
